{"name": "Проверяем, что юзер не может залогиниться с невалидным логином или паролем, запрос возвращает ошибку с кодом 401", "status": "passed", "start": 1731761856371, "stop": 1731761856505, "uuid": "191b0d4b-0d31-4d16-b523-5aac7527cc2f", "historyId": "b93192e63eaadafa1a2d06a5306d55bc", "testCaseId": "b93192e63eaadafa1a2d06a5306d55bc", "fullName": "tests.test_login_user.TestLoginUser#test_courier_login_with_not_existing_user_error_401", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "hanastasia-mbby"}, {"name": "thread", "value": "1011-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}